### PR TITLE
fix: fixed hovering color change issue

### LINKED ISSUE #161: Hovering over test on test-list removes the color
- when a user hovers over a test, the color goes away
Screen Shot 2020-07-27 at 1 41 36 PM

### LINKED ISSUE #194: Implement proper coloring on org/repo page according to threshold of percent passing
- make sure all indicating colors are consistent between org and repo page and reflect failing/flaky/passing correctly

### PR DESCRIPTION
**Pull request by madelyndubuk**
- when hovering over a test, the opacity changes, but not the color
Screenshot 2020-07-28 at 11 32 39 AM
- added color to text of passing percentage based on threshold value of 90% for currently passing tests
Screenshot 2020-07-30 at 12 32 58 PM
- for tests passing less than 90% of the time, the text will show red
Screenshot 2020-07-30 at 12 33 06 PM
- Fixes #194 
- Fixes #161

### CODE REVIEW

**Comment by gis727** [comment]
LGTM !
@madelyndubuk , we should probably use the same green color you have for the repositories on the organization page.

**Comment by madelyndubuk** [comment]
@gis727 @bcoe Agreed! we can wait to land this until we hear from the designer, that sounds good to me!

**Comment by bcoe** [comment]
@madelyndubuk @gis727 I happened to be talking to my partner who's a designer last night, they thought the green was a bit much (_this is just one other opinion of course_).

They wondered, what if for warning and failure events we instead had a little green check box icon, and/or warning icon:

[⚠️   this is a flaky test]
[ ✅  this is a healthy test]

**Comment by madelyndubuk** [comment]
@bcoe @gis727 That could be a good idea! Are you saying all the boxes would be white and then flaky tests would have the warning icon, passing tests would have the green check, and would failing tests have a red X icon or something similar? Or just remove the green color and keep the red and yellow color in addition to adding the icons?

**Comment by bcoe** [comment]
@madelyndubuk I think it's fine to keep red the way it is, with the hover fix, we want to draw loud attention to failures.

But for flaky and passing tests, I think the white background with an icon could do the trick?

**Comment by gis727** [comment]
Wonderful idea !
We will have to do the same for the repo page then.

**Comment by madelyndubuk** [comment]
I agree! Okay, will do that now

**Pull request merged**
